name    'ft-methode_api'
version '${project.version}'
source 'UNKNOWN'
author 'ft'
license 'UNKNOWN'
summary 'UNKNOWN'
description 'UNKNOWN'
project_page 'UNKNOWN'

## Add dependencies, if any:
# dependency 'username/name', '>= 1.2.0'
dependency 'ft/runnablejar', '2.2.0'
dependency 'ft/nagios', '>=1.1.29'
