name    'ft-methode_api'
version '${project.version}'
source 'UNKNOWN'
author 'ft'
license 'UNKNOWN'
summary 'UNKNOWN'
description 'UNKNOWN'
project_page 'UNKNOWN'

## Add dependencies, if any:
# dependency 'username/name', '>= 1.2.0'
dependency 'ft/content_runnablejar', '1.1.x'
dependency 'ft/content_platform_nagios', '2.x'
dependency 'ft/sudoers_sudocont', '>=0.0.1'
